### ISSUE TITLE
[Umidigi A1 Pro] MTK RIL broken?

### ISSUE THREAD

**Issue by RalphMalph1** [phhusson/treble_experimentations#122]
Hello,

I have IMEI-numbers.
When I start the phone I have to put the sim-pin.
But I cannot make a call and I have no internet.
In the Telegram-chat I heard RIL is broken for MTK on GSI. 

Need for logfile? Or you know what the problem is?

Greetings,
Ralph

**Comment by phhusson** [comment]
What phone? MTK chip? Android version? Mono-sim?

**Comment by RalphMalph1** [comment]
Umidigi A1 Pro
MT6739 
Dual SIM, Dual 4G 
Stock Android 8.1

**Comment by phhusson** [comment]
Ok, first try with only one SIM

**Comment by RalphMalph1** [comment]
yes, I had one sim in it (but was not working). After my lunch I will try again from scratch. But since I heard ril was broken on mtk I thought maybe you need some log

**Comment by phhusson** [comment]
It's not /that/ broken
Dual-SIM doesn't work, incoming calls doesn't work, but that's all
Outgoing calls work, and data works

**Comment by RalphMalph1** [comment]
For me nothing is working, not incoming , not outgoing.
Signal-symbol is full, data is working, but trying to make a phonecall directly disconnects (not even calling).

[umidigi_a1_not_calling_booting.txt](https://github.com/phhusson/treble_experimentations/files/2180181/umidigi_a1_not_calling_booting.txt)
[umidigi_a1_not_calling_1.txt](https://github.com/phhusson/treble_experimentations/files/2180182/umidigi_a1_not_calling_1.txt)

**Comment by phhusson** [comment]
"nothing is working" = there is signal, and data is working, ok.

**Comment by RalphMalph1** [comment]
sorry , nothing with calling

**Comment by Stephelyn1210** [comment]
Works for me, except calling my Device and force closing system ui while long pressing power button...

**Comment by RalphMalph1** [comment]
Which device?
Whick twrp?
Which rom?

**Comment by Stephelyn1210** [comment]
My device is Cherry Mobile Omega Lite 4 running MTK6580 with Android 8.1.0 Go Edition Treble ready, TWRP 3.2.1... I set my apn to my default, because apn is not set in first boot...

**Comment by Skyrimus** [comment]
Of course, see issue #57

**Comment by Stephelyn1210** [comment]
And what about this system ui force closing? Pressing power button for few seconds?

**Comment by Skyrimus** [comment]
I don t have this problem, maybe you not wipe dalvik :)

**Comment by Stephelyn1210** [comment]
I wipe data, cache and dalvik.. I do clean install.. Same problem..

**Comment by Attedz** [comment]
I had the same problem with Moto G6 Plus. Try to change SIM card to another slot.

**Comment by Zap123** [comment]
Asus Zenfone Go(MTK 6580) Dual SIM, both signals works, making calls works, incoming calls doesn't work. This project is amazing, this is an Android 5 phone with a custom Oreo ROM.

**Comment by Skyrimus** [comment]
Zap123, this is a same problem on mt6580

**Comment by RalphMalph1** [comment]
Changing sim to another slot, doesnt make a difference.
I will make new logcat later today. Also tried Resurrection-Treble, but same thing.
Too bad :-(

**Comment by RalphMalph1** [comment]
Now pre-release v23.
Calling out works
Data works
Incoming calls not 

almost there , keep on the good work.
Hope soon everything works

**Comment by RalphMalph1** [comment]
[INcall_not working.txt](https://github.com/phhusson/treble_experimentations/files/2280270/INcall_not.working.txt)

I have v23 pre-release running. Outgoing calls work. 4G data works. Incoming calls not working. Here is the logcat from me calling to the phone. Phone is not responsing anything.

**Comment by phhusson** [comment]
Fixed in https://github.com/phhusson/device_phh_treble/commit/3e655b7c4b737d687388cb466a7a99e93242b7cb

**Comment by penn5** [comment]
I agree it's fixed but it's also not fixed, many devices with identical issue need to be done through hal instead of hexedit. Open another issue for implementing mtk radio ex?

**Comment by phhusson** [comment]
Like this you mean?
https://github.com/phhusson/platform_frameworks_opt_telephony/commit/04a9d8b4582f52b0371fa5c8e863c32b19b97b2b
