### ISSUE TITLE
Galaxy A11 (SM-A115U1, a11q) - Watchdog panic on v4XX.

### ISSUE THREAD

**Issue by starfoxdot64** [phhusson/treble_experimentations#2296]
SOC: SD450
Arch: arm32_binder64

Symptoms: After a clean flash (system/data/cache wiped), all of the v4XX builds lock up and reset after about 100 seconds after init takes over. The system runs alright, thinking the device is being emulated but pulling the correct specifications in the short amount if time I could interact with the system. The system also does not show the boot animation, but that doesn't defer from normal operation.

```
Steps to reproduce:
    1. Flash a v4XX system image.
        - in my case I used v412's a64 gogapps variant.
    2. Wipe/reformat /data to remove device encryption.
    3. Restart to system, skip all setup wizard steps.
    4. About 30 to 45 seconds after setup.
        - The phone will lock up for about 3 seconds, log a panic to pstore, then hard-reset.
```

Files:
[ramoops_logs.zip (3 files, first boot attempt)](https://github.com/phhusson/treble_experimentations/files/8596112/ramoops_logs.zip)
[ramoops_logs.zip (3 files, second boot attempt)](https://github.com/phhusson/treble_experimentations/files/8596120/ramoops_logs.zip)

More than willing to test a couple builds, if that's what patching for it takes.

**Comment by phhusson** [comment]
Do you use magisk? Secure variant?
How many /dev/watchdog* devices so you see/which?

Apr 30, 2022 07:07:50 Jay ***@***.***>:

**Comment by starfoxdot64** [comment]
I'm not using magisk, no. 

Here's what I have present in /dev for watchdogs:

```
/dev/watchdog
/dev/watchdog0
/dev/watchdog1
```

**Comment by UDPSendToFailed** [comment]
Not sure if this is relevant, but I'm having the same issue with Samsung SM-T590 (Snapdragon 450, 3.18 kernel). 
I managed to fix the panic with disabling software watchdog by setting CONFIG_SOFT_WATCHDOG=n in kernel defconfig. 

However that didn't fix the root cause, although the kernel doesn't crash now, the system still enters "zombie mode" after ~110 seconds of uptime, apps can't be opened, half of the functions like quick toggles are working but eventually the system will return to the boot animation. This happens with both GSI systems and my non-GSI build. 

Here is a crash log before disabling software watchdog:
```
<0>[  110.560296] I[6:      swapper/6:    0] Kernel panic - not syncing: Software Watchdog Timer expired
<6>[  110.560425] I[6:      swapper/6:    0] CPU: 6 PID: 0 Comm: swapper/6 Tainted: G        W      3.18.140Slayer #5
<6>[  110.560531] I[6:      swapper/6:    0] Hardware name: Samsung Tab A2 XL WIFI EUR OPEN Rev04 (DT)
<0>[  110.560625] I[6:      swapper/6:    0] Call trace:
<6>[  110.560697] I[6:      swapper/6:    0] [<ffffffc00008bec4>] dump_backtrace+0x0/0x128
<6>[  110.560785] I[6:      swapper/6:    0] [<ffffffc00008c000>] show_stack+0x14/0x1c
<6>[  110.560878] I[6:      swapper/6:    0] [<ffffffc00124b3f4>] dump_stack+0x84/0xa8
<6>[  110.560982] I[6:      swapper/6:    0] [<ffffffc001249b88>] panic+0x1a4/0x388
<6>[  110.561085] I[6:      swapper/6:    0] [<ffffffc000aa40c4>] dm_send_uevents+0x0/0x170
<6>[  110.561188] I[6:      swapper/6:    0] [<ffffffc00011eeec>] call_timer_fn+0x4c/0x1c4
<6>[  110.561285] I[6:      swapper/6:    0] [<ffffffc00011fc5c>] run_timer_softirq+0x294/0x61c
<6>[  110.561390] I[6:      swapper/6:    0] [<ffffffc0000b3134>] __do_softirq+0x104/0x3fc
<6>[  110.561483] I[6:      swapper/6:    0] [<ffffffc0000b3700>] irq_exit+0x9c/0xcc
<6>[  110.561575] I[6:      swapper/6:    0] [<ffffffc00010cdf4>] __handle_domain_irq+0x78/0xc8
<6>[  110.561668] I[6:      swapper/6:    0] [<ffffffc0000828a0>] gic_handle_irq+0x4c/0xa8
<6>[  110.561761] I[6:      swapper/6:    0] Exception stack(0xffffffc0ae2fbcf0 to 0xffffffc0ae2fbe20)
<6>[  110.561866] I[6:      swapper/6:    0] bce0:                                     00000000 00000000 00000000 00000080
<6>[  110.561991] I[6:      swapper/6:    0] bd00: 421f9000 00000000 00ad9bb4 ffffffc0 60400145 00000000 ffffffe0 00000000
<6>[  110.562128] I[6:      swapper/6:    0] bd20: 00b42eb6 00000000 000003e8 00000000 34155555 00000000 0000a33e 00000000
<6>[  110.562251] I[6:      swapper/6:    0] bd40: 00000018 00000000 a1b42400 001d8119 82eb19b5 00000000 6b63482c 65762764
<6>[  110.562375] I[6:      swapper/6:    0] bd60: 7f7f7f7f 7f7f7f7f a8ff2868 fefefebf ff7f7f7f ffffffff 01010101 01010101
<6>[  110.562485] I[6:      swapper/6:    0] bd80: 00000010 00000000 00000038 00000000 ffffffff 0fffffff 00000400 00000000
<6>[  110.562593] I[6:      swapper/6:    0] bda0: 001b8a00 00000000 00000466 00000000 0000000e 00000000 00000000 00000000
<6>[  110.562702] I[6:      swapper/6:    0] bdc0: 00002e20 00000000 001685d6 00000000 01c527f8 ffffffc0 af9e9378 ffffffc0
<6>[  110.562811] I[6:      swapper/6:    0] bde0: 000001b6 00000000 aa36cc18 ffffffc0 00000001 00000000 01ba0ab8 ffffffc0
<6>[  110.562937] I[6:      swapper/6:    0] be00: bde3c2d1 00000019 ae2fbe50 ffffffc0 00ad9b90 ffffffc0 ae2fbe50 ffffffc0
<6>[  110.563065] I[6:      swapper/6:    0] [<ffffffc0000861b4>] el1_irq+0xb4/0x158
<6>[  110.563162] I[6:      swapper/6:    0] [<ffffffc000ad4230>] cpuidle_enter_state+0x80/0x260
<6>[  110.563252] I[6:      swapper/6:    0] [<ffffffc000ad4658>] cpuidle_enter+0x18/0x20
<6>[  110.563341] I[6:      swapper/6:    0] [<ffffffc0000fc434>] cpu_startup_entry+0x320/0x38c
<6>[  110.563442] I[6:      swapper/6:    0] [<ffffffc000090ef4>] secondary_start_kernel+0xf8/0x11c
<2>[  110.563577] I[4:     logd.klogd:  453] CPU4: stopping
<6>[  110.563646] I[4:     logd.klogd:  453] 
<6>[  110.563708] I[4:     logd.klogd:  453] CPU: 4 PID: 453 Comm: logd.klogd Tainted: G        W      3.18.140Slayer #5
<6>[  110.563821] I[4:     logd.klogd:  453] Hardware name: Samsung Tab A2 XL WIFI EUR OPEN Rev04 (DT)
<6>[  110.563924] I[4:     logd.klogd:  453] task: ffffffc0a812c100 ti: ffffffc0a800c000 task.ti: ffffffc0a800c000
<6>[  110.564036] I[4:     logd.klogd:  453] PC is at 0x7e1035c0a4
<6>[  110.564109] I[4:     logd.klogd:  453] LR is at 0x7e1035f174
<6>[  110.564182] I[4:     logd.klogd:  453] pc : [<0000007e1035c0a4>] lr : [<0000007e1035f174>] pstate: 80000000
<6>[  110.564290] I[4:     logd.klogd:  453] sp : 0000007b7bd2f490
<6>[  110.564363] I[4:     logd.klogd:  453] x29: 0000007b7bd2f4b0 x28: 0000000000000001 
<6>[  110.564463] I[4:     logd.klogd:  453] x27: 0000000000007fff x26: 7fffffffffffffff 
<6>[  110.564559] I[4:     logd.klogd:  453] x25: ffffffffffffffff x24: 0000007b7bd31000 
<6>[  110.564655] I[4:     logd.klogd:  453] x23: 0000000000003fff x22: 0000007b7bd31000 
<6>[  110.564750] I[4:     logd.klogd:  453] x21: 0000007b7bd2f560 x20: 0000000000000001 
<6>[  110.564846] I[4:     logd.klogd:  453] x19: 0000007d5f033010 x18: 0000007b7b036000 
<6>[  110.564941] I[4:     logd.klogd:  453] x17: 0000000000000006 x16: 0000000000000000 
<6>[  110.565037] I[4:     logd.klogd:  453] x15: 0000000000000006 x14: 0000000000000004 
<6>[  110.565132] I[4:     logd.klogd:  453] x13: 0000000000000002 x12: 0000007e102e320c 
<6>[  110.565226] I[4:     logd.klogd:  453] x11: 0000000000000000 x10: 0000000000000000 
<6>[  110.565320] I[4:     logd.klogd:  453] x9 : 0000000000000000 x8 : 0000000000000000 
<6>[  110.565416] I[4:     logd.klogd:  453] x7 : 00000000c28f5c29 x6 : 0000000080000000 
<6>[  110.565511] I[4:     logd.klogd:  453] x5 : fffffffffffffe93 x4 : 0000000051eb851f 
<6>[  110.565607] I[4:     logd.klogd:  453] x3 : 0000007b7bd2f560 x2 : 0000000000000001 
<6>[  110.565702] I[4:     logd.klogd:  453] x1 : 0000007b7bd2f5e0 x0 : 0000007d5f033010 
<6>[  110.565796] I[4:     logd.klogd:  453] 
<6>[  110.565855] I[4:     logd.klogd:  453] CPU: 4 PID: 453 Comm: logd.klogd Tainted: G        W      3.18.140Slayer #5
<6>[  110.565969] I[4:     logd.klogd:  453] Hardware name: Samsung Tab A2 XL WIFI EUR OPEN Rev04 (DT)
<0>[  110.566068] I[4:     logd.klogd:  453] Call trace:
<6>[  110.566139] I[4:     logd.klogd:  453] [<ffffffc00008bec4>] dump_backtrace+0x0/0x128
<6>[  110.566235] I[4:     logd.klogd:  453] [<ffffffc00008c000>] show_stack+0x14/0x1c
<6>[  110.566329] I[4:     logd.klogd:  453] [<ffffffc00124b3f4>] dump_stack+0x84/0xa8
<6>[  110.566420] I[4:     logd.klogd:  453] [<ffffffc000091798>] handle_IPI+0x334/0x4c8
<6>[  110.566512] I[4:     logd.klogd:  453] [<ffffffc0000828f8>] gic_handle_irq+0xa4/0xa8
<6>[  110.566604] I[4:     logd.klogd:  453] Exception stack(0xffffffc0a800fe90 to 0xffffffc0a800ffc0)
```

**Comment by starfoxdot64** [comment]
> Not sure if this is relevant, but I'm having the same issue with Samsung SM-T590 (Snapdragon 450, 3.18 kernel). I managed to fix the panic with disabling software watchdog by setting CONFIG_SOFT_WATCHDOG=n in kernel defconfig.
> 
> However that didn't fix the root cause, although the kernel doesn't crash now, the system still enters "zombie mode" after ~110 seconds of uptime, apps can't be opened, half of the functions like quick toggles are working but eventually the system will return to the boot animation. This happens with both GSI systems and my non-GSI build.
> 
> The only "fix" I found so far is force restarting again and again until it boots up correctly.
> 
> Here is a crash log before disabling software watchdog:
> 
> ```
> <0>[  110.560296] I[6:      swapper/6:    0] Kernel panic - not syncing: Software Watchdog Timer expired
> <6>[  110.560425] I[6:      swapper/6:    0] CPU: 6 PID: 0 Comm: swapper/6 Tainted: G        W      3.18.140Slayer #5
> <6>[  110.560531] I[6:      swapper/6:    0] Hardware name: Samsung Tab A2 XL WIFI EUR OPEN Rev04 (DT)
> <0>[  110.560625] I[6:      swapper/6:    0] Call trace:
> <6>[  110.560697] I[6:      swapper/6:    0] [<ffffffc00008bec4>] dump_backtrace+0x0/0x128
> <6>[  110.560785] I[6:      swapper/6:    0] [<ffffffc00008c000>] show_stack+0x14/0x1c
> <6>[  110.560878] I[6:      swapper/6:    0] [<ffffffc00124b3f4>] dump_stack+0x84/0xa8
> <6>[  110.560982] I[6:      swapper/6:    0] [<ffffffc001249b88>] panic+0x1a4/0x388
> <6>[  110.561085] I[6:      swapper/6:    0] [<ffffffc000aa40c4>] dm_send_uevents+0x0/0x170
> <6>[  110.561188] I[6:      swapper/6:    0] [<ffffffc00011eeec>] call_timer_fn+0x4c/0x1c4
> <6>[  110.561285] I[6:      swapper/6:    0] [<ffffffc00011fc5c>] run_timer_softirq+0x294/0x61c
> <6>[  110.561390] I[6:      swapper/6:    0] [<ffffffc0000b3134>] __do_softirq+0x104/0x3fc
> <6>[  110.561483] I[6:      swapper/6:    0] [<ffffffc0000b3700>] irq_exit+0x9c/0xcc
> <6>[  110.561575] I[6:      swapper/6:    0] [<ffffffc00010cdf4>] __handle_domain_irq+0x78/0xc8
> <6>[  110.561668] I[6:      swapper/6:    0] [<ffffffc0000828a0>] gic_handle_irq+0x4c/0xa8
> <6>[  110.561761] I[6:      swapper/6:    0] Exception stack(0xffffffc0ae2fbcf0 to 0xffffffc0ae2fbe20)
> <6>[  110.561866] I[6:      swapper/6:    0] bce0:                                     00000000 00000000 00000000 00000080
> <6>[  110.561991] I[6:      swapper/6:    0] bd00: 421f9000 00000000 00ad9bb4 ffffffc0 60400145 00000000 ffffffe0 00000000
> <6>[  110.562128] I[6:      swapper/6:    0] bd20: 00b42eb6 00000000 000003e8 00000000 34155555 00000000 0000a33e 00000000
> <6>[  110.562251] I[6:      swapper/6:    0] bd40: 00000018 00000000 a1b42400 001d8119 82eb19b5 00000000 6b63482c 65762764
> <6>[  110.562375] I[6:      swapper/6:    0] bd60: 7f7f7f7f 7f7f7f7f a8ff2868 fefefebf ff7f7f7f ffffffff 01010101 01010101
> <6>[  110.562485] I[6:      swapper/6:    0] bd80: 00000010 00000000 00000038 00000000 ffffffff 0fffffff 00000400 00000000
> <6>[  110.562593] I[6:      swapper/6:    0] bda0: 001b8a00 00000000 00000466 00000000 0000000e 00000000 00000000 00000000
> <6>[  110.562702] I[6:      swapper/6:    0] bdc0: 00002e20 00000000 001685d6 00000000 01c527f8 ffffffc0 af9e9378 ffffffc0
> <6>[  110.562811] I[6:      swapper/6:    0] bde0: 000001b6 00000000 aa36cc18 ffffffc0 00000001 00000000 01ba0ab8 ffffffc0
> <6>[  110.562937] I[6:      swapper/6:    0] be00: bde3c2d1 00000019 ae2fbe50 ffffffc0 00ad9b90 ffffffc0 ae2fbe50 ffffffc0
> <6>[  110.563065] I[6:      swapper/6:    0] [<ffffffc0000861b4>] el1_irq+0xb4/0x158
> <6>[  110.563162] I[6:      swapper/6:    0] [<ffffffc000ad4230>] cpuidle_enter_state+0x80/0x260
> <6>[  110.563252] I[6:      swapper/6:    0] [<ffffffc000ad4658>] cpuidle_enter+0x18/0x20
> <6>[  110.563341] I[6:      swapper/6:    0] [<ffffffc0000fc434>] cpu_startup_entry+0x320/0x38c
> <6>[  110.563442] I[6:      swapper/6:    0] [<ffffffc000090ef4>] secondary_start_kernel+0xf8/0x11c
> <2>[  110.563577] I[4:     logd.klogd:  453] CPU4: stopping
> <6>[  110.563646] I[4:     logd.klogd:  453] 
> <6>[  110.563708] I[4:     logd.klogd:  453] CPU: 4 PID: 453 Comm: logd.klogd Tainted: G        W      3.18.140Slayer #5
> <6>[  110.563821] I[4:     logd.klogd:  453] Hardware name: Samsung Tab A2 XL WIFI EUR OPEN Rev04 (DT)
> <6>[  110.563924] I[4:     logd.klogd:  453] task: ffffffc0a812c100 ti: ffffffc0a800c000 task.ti: ffffffc0a800c000
> <6>[  110.564036] I[4:     logd.klogd:  453] PC is at 0x7e1035c0a4
> <6>[  110.564109] I[4:     logd.klogd:  453] LR is at 0x7e1035f174
> <6>[  110.564182] I[4:     logd.klogd:  453] pc : [<0000007e1035c0a4>] lr : [<0000007e1035f174>] pstate: 80000000
> <6>[  110.564290] I[4:     logd.klogd:  453] sp : 0000007b7bd2f490
> <6>[  110.564363] I[4:     logd.klogd:  453] x29: 0000007b7bd2f4b0 x28: 0000000000000001 
> <6>[  110.564463] I[4:     logd.klogd:  453] x27: 0000000000007fff x26: 7fffffffffffffff 
> <6>[  110.564559] I[4:     logd.klogd:  453] x25: ffffffffffffffff x24: 0000007b7bd31000 
> <6>[  110.564655] I[4:     logd.klogd:  453] x23: 0000000000003fff x22: 0000007b7bd31000 
> <6>[  110.564750] I[4:     logd.klogd:  453] x21: 0000007b7bd2f560 x20: 0000000000000001 
> <6>[  110.564846] I[4:     logd.klogd:  453] x19: 0000007d5f033010 x18: 0000007b7b036000 
> <6>[  110.564941] I[4:     logd.klogd:  453] x17: 0000000000000006 x16: 0000000000000000 
> <6>[  110.565037] I[4:     logd.klogd:  453] x15: 0000000000000006 x14: 0000000000000004 
> <6>[  110.565132] I[4:     logd.klogd:  453] x13: 0000000000000002 x12: 0000007e102e320c 
> <6>[  110.565226] I[4:     logd.klogd:  453] x11: 0000000000000000 x10: 0000000000000000 
> <6>[  110.565320] I[4:     logd.klogd:  453] x9 : 0000000000000000 x8 : 0000000000000000 
> <6>[  110.565416] I[4:     logd.klogd:  453] x7 : 00000000c28f5c29 x6 : 0000000080000000 
> <6>[  110.565511] I[4:     logd.klogd:  453] x5 : fffffffffffffe93 x4 : 0000000051eb851f 
> <6>[  110.565607] I[4:     logd.klogd:  453] x3 : 0000007b7bd2f560 x2 : 0000000000000001 
> <6>[  110.565702] I[4:     logd.klogd:  453] x1 : 0000007b7bd2f5e0 x0 : 0000007d5f033010 
> <6>[  110.565796] I[4:     logd.klogd:  453] 
> <6>[  110.565855] I[4:     logd.klogd:  453] CPU: 4 PID: 453 Comm: logd.klogd Tainted: G        W      3.18.140Slayer #5
> <6>[  110.565969] I[4:     logd.klogd:  453] Hardware name: Samsung Tab A2 XL WIFI EUR OPEN Rev04 (DT)
> <0>[  110.566068] I[4:     logd.klogd:  453] Call trace:
> <6>[  110.566139] I[4:     logd.klogd:  453] [<ffffffc00008bec4>] dump_backtrace+0x0/0x128
> <6>[  110.566235] I[4:     logd.klogd:  453] [<ffffffc00008c000>] show_stack+0x14/0x1c
> <6>[  110.566329] I[4:     logd.klogd:  453] [<ffffffc00124b3f4>] dump_stack+0x84/0xa8
> <6>[  110.566420] I[4:     logd.klogd:  453] [<ffffffc000091798>] handle_IPI+0x334/0x4c8
> <6>[  110.566512] I[4:     logd.klogd:  453] [<ffffffc0000828f8>] gic_handle_irq+0xa4/0xa8
> <6>[  110.566604] I[4:     logd.klogd:  453] Exception stack(0xffffffc0a800fe90 to 0xffffffc0a800ffc0)
> ```


While that initially sounded like it'd work, I have no third party kernels available for my model. There's literally no software support for this device, so I don't even have a proper kernel outside of stock.

**Comment by UDPSendToFailed** [comment]
Oh I forgot to mention that both stock and custom kernels are having the same issue as your device has.

**Comment by starfoxdot64** [comment]
> Oh I forgot to mention that both stock and custom kernels are having the same issue as your device has.

Hm... odd. Maybe it's a Samsung thing?

**Comment by UDPSendToFailed** [comment]
> Hm... odd. Maybe it's a Samsung thing?

I guess something with either the vendor libraries or the kernel. Have you tried disabling the software watchdog on stock kernel? I wonder if there is any similarity in the crash logs after an unsuccessful boot. Here is mine but I can't find the actual cause: 
[crash.txt](https://github.com/phhusson/treble_experimentations/files/8596755/crash.txt)

**Comment by phhusson** [comment]
Since you didn't answer, I'm assuming you're using secure variant.
Could you confirm the issue doesn't happen on non-secure variant please?

Also, this issue should be fixed since a long time ago by https://github.com/phhusson/device_phh_treble/blob/android-12.0/rw-system.sh#L1011 maybe you can try doing this yourself to see why it fails

**Comment by starfoxdot64** [comment]
> Since you didn't answer, I'm assuming you're using secure variant.
> Could you confirm the issue doesn't happen on non-secure variant please?


Right, sorry. This isn't the secure variant, but I'll try that next.

**Comment by starfoxdot64** [comment]
> Since you didn't answer, I'm assuming you're using secure variant. Could you confirm the issue doesn't happen on non-secure variant please?
> 
> Also, this issue should be fixed since a long time ago by https://github.com/phhusson/device_phh_treble/blob/android-12.0/rw-system.sh#L1011 maybe you can try doing this yourself to see why it fails

Alright, so secure variant still fails, and so do the vanilla versions. I'm looking into the existing rw-system.sh and by the looks of it, that line does exist in it. I'm not sure what I'm expected to do with the 12.0 variant though - Did you want me to try echoing the same thing to /dev/watchdog0, so only /dev/watchdog is left untouched?

**Comment by starfoxdot64** [comment]
Closing the thread, now that rw-system.sh is patched. Looks like the Galaxy A11 is going back to bootable status.

([commit](https://github.com/phhusson/device_phh_treble/commit/b4a09c8531e0d274db413c8cbf4f130ddf928e7b))
