### ISSUE TITLE
MTK No Internet

### ISSUE THREAD

**Issue by Evgenie3311** [phhusson/treble_experimentations#2627]
### Current Behavior:
No signal, but i can receive calls and SMS.
  
### Describe the bug
No signal, i can't open apps with internet access required.

### To Reproduce
1. Install GSI
2. Reboot to GSI
3. See problem

### Expected behavior
Working internet.

### Smartphone (please complete the following information):
 - Device: Galaxy A04
 - Build Flavor: All ROMs
 - Version [e.g. V412]

### Additional context
In logcat i can see that repeating all the time:
```
05-30 19:30:40.339  1536  1551 D ConnectivityService: registerNetworkAgent NetworkAgentInfo{network{153}  handle{660535693325}  ni{MOBILE[LTE] CONNECTING extra: internet.beeline.ru} created=2024-05-30T16:30:40.339Z Score(Policies :  ; KeepConnected : 0)   lp{{LinkAddresses: [ ] DnsAddresses: [ ] Domains: null MTU: 0 Routes: [ ]}}  nc{[ Transports: CELLULAR Capabilities: SUPL&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_ROAMING&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=14Kbps LinkDnBandwidth>=14Kbps Specifier: <TelephonyNetworkSpecifier [mSubId = 1]> SubscriptionIds: {1} UnderlyingNetworks: Null]}  factorySerialNumber=6}
05-30 19:30:40.344  1016  1016 I netd    : getFwmarkForNetwork(153) -> {MarkMaskParcel{mark: 153, mask: 65535}} <0.02ms>
05-30 19:30:40.348  1536  2116 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcastMultiplePermissions:1304 android.content.Context.sendBroadcastMultiplePermissions:2443 android.content.Context.sendBroadcastMultiplePermissions:2431 com.android.server.TelephonyRegistry.broadcastDataConnectionStateChanged:3805 com.android.server.TelephonyRegistry.notifyDataConnectionForSubscriber:2197
05-30 19:30:40.363  2039  2039 D ShadeCarrierGroup: ignoring old pipeline callback because new mobile icon is enabled
05-30 19:30:40.369  1536  1943 D ConnectivityService: [153 CELLULAR] EVENT_NETWORK_INFO_CHANGED, going from CONNECTING to CONNECTING
05-30 19:30:40.372  2306  4752 D NetworkMonitor/153: checkAndRenewResourceConfig: update captive portal https urls to [https://www.google.com/generate_204]
05-30 19:30:40.373  2306  4752 D NetworkMonitor/153: checkAndRenewResourceConfig: update captive portal http urls to [http://connectivitycheck.gstatic.com/generate_204]
05-30 19:30:40.373  2306  4752 D NetworkMonitor/153: checkAndRenewResourceConfig: update captive portal fallback urls to[http://www.google.com/gen_204, http://play.googleapis.com/generate_204]
05-30 19:30:40.373  2306  4752 D NetworkMonitor: Starting on network 153 with capport HTTPS URL [https://www.google.com/generate_204] and HTTP URL [http://connectivitycheck.gstatic.com/generate_204]
05-30 19:30:40.372  1303  1303 W ESAR2   : type=1400 audit(0.0:441): avc:  denied  { open } for  path="/dev/__properties__/u:object_r:default_prop:s0" dev="tmpfs" ino=9224 scontext=u:r:rild:s0 tcontext=u:object_r:default_prop:s0 tclass=file permissive=0
05-30 19:30:40.377  1303  1472 W libc    : Access denied finding property "persist.ril.supportNrModefromCp"
05-30 19:30:40.403  1201  1321 I Light   : light data = 4.000000 .
05-30 19:30:40.433  1536  1551 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcastMultiplePermissions:1304 android.content.Context.sendBroadcastMultiplePermissions:2443 android.content.Context.sendBroadcastMultiplePermissions:2431 com.android.server.TelephonyRegistry.broadcastDataConnectionStateChanged:3805 com.android.server.TelephonyRegistry.notifyDataConnectionForSubscriber:2197
05-30 19:30:40.440  1536  1943 D ConnectivityService: [153 CELLULAR] EVENT_NETWORK_INFO_CHANGED, going from CONNECTING to DISCONNECTED
05-30 19:30:40.440  1536  1943 D ConnectivityService: [153 CELLULAR] disconnected, was satisfying 0
05-30 19:30:40.447  2039  2039 D ShadeCarrierGroup: ignoring old pipeline callback because new mobile icon is enabled
05-30 19:30:40.448  1536  1943 W BestClock: java.time.DateTimeException: Missing network time fix
05-30 19:30:40.455  1016  1016 I netd    : tetherGetStats() -> {[]} <3.67ms>
05-30 19:30:40.460  1536  1943 W BestClock: java.time.DateTimeException: Missing network time fix
05-30 19:30:40.468  1016  1016 I netd    : setNetworkAllowlist([]) <0.03ms>
05-30 19:30:40.472  1536  1943 D ConnectivityService: NetReassign [no changes] [c 1] [a 0] [i 2]
```

**Comment by phhusson** [comment]
Try with `logcat -b all`

**Comment by Evgenie3311** [comment]
> logcat -b all

[1.txt](https://github.com/user-attachments/files/15522234/1.txt)

**Comment by Evgenie3311** [comment]
and i cant get sms

**Comment by jasonmerc** [comment]
I am also having this issue.  Running a TCL Ion V (helio G25 that came with A13 stock).  I am having this issue on both Lineage 20 and Lineage 21 TD builds.

Please let me know if there's anything I can do to help.

**Comment by Evgenie3311** [comment]
> I am also having this issue. Running a TCL Ion V, MTK Helio G25 that came with A13 stock. I am having this issue on both Lineage 20 and Lineage 21 TD builds. Carrier is Total by Verizon if that matters (Tracfone based company I believe).
> 
> Please let me know if there's anything I can do to help.
> 
> EDIT: looks like I can send SMS, receive SMS, places calls, receive calls. It just won't let me use LTE for data. No LTE icon next to the signal bars even though VoLTE is enabled and works just fine with the above tests.

I'm can receive and do calls, send sms and that's all. When i'm tried to turn off my SIM-card, it just disappeared and it can't be turned on again until i restart GSI

**Comment by Evgenie3311** [comment]
fixed it by replacing my main sim card to sim 1 slot.

**Comment by jasonmerc** [comment]
Damn I think its still broken for me, but I'll check again as soon as I can pull backups from the stock firmware again (an update got pushed).

**Comment by jasonmerc** [comment]
Still have broken data on my GSI despite all stock firmware updates, any fixes?  I don't have multiple SIM trays.
