### ISSUE TITLE
[P10-Plus] Brightness slider doesnt work

### ISSUE THREAD

**Issue by MartB** [phhusson/treble_experimentations#34]
Hey,

Brightness control works when i manually write values:
`/sys/class/leds/lcd_backlight0 # echo '1500' > brightness`

**Log excerpt**:
```
[...]
05-12 15:03:05.715 11103 11103 I ls      : type=1400 audit(0.0:1197): avc: denied { read } for name="lcd_backlight0" dev="sysfs" ino=34380 scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=1
05-12 15:03:05.715 11103 11103 I ls      : type=1400 audit(0.0:1198): avc: denied { open } for path="/sys/devices/platform/hisi_fb.1048577/leds/lcd_backlight0" dev="sysfs" ino=34380 scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=1
05-12 15:03:05.715 11103 11103 I ls      : type=1400 audit(0.0:1199): avc: denied { getattr } for path="/sys/devices/platform/hisi_fb.1048577/leds/lcd_backlight0/max_brightness" dev="sysfs" ino=34386 scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
[...]
05-12 15:10:28.763 10943 10943 I sh      : type=1400 audit(0.0:1206): avc: denied { write } for name="brightness" dev="sysfs" ino=34385 scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:sysfs_backlight:s0 tclass=file permissive=1
```

I hope that is enough to get it fixed, otherwise feel free to ask for more info.

**Comment by phhusson** [comment]
All those logs say permissive=1 so no error there

**Comment by MartB** [comment]
Hm damn i overlooked that one.
I attached the full log, hopefully you can make sth out of it, because im stuck for now.
[hw10p-dev.log](https://github.com/phhusson/treble_experimentations/files/1997666/hw10p-dev.log)

**Comment by kaiomatico** [comment]
Try the v18 build please, on my Honor 9 Lite it was fixed with v18 :)

**Comment by phhusson** [comment]
Can you confirm this is still an issue?
I haven't heard anyone mention it again.

**Comment by Dil3mm4** [comment]
This doesn't seem to be an issue anymore, maybe it can be closed. @phhusson
