### ISSUE TITLE
[Bounty] Fix SMS receive on MT6739

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#373]
The reference device which will be used for this bug bounty is an Infinix Smart 2, running an SFR (French operator) single SIM.
This bounty will be considered fulfilled if the submitter provides sources that can be integrated into Phh-Treble GSI Pie that fixes this test-case.

Hopefully, this will fix this issue on all MTK devices, but that's not guaranteed.

Current total: $15
Subdivision:
- @phhusson $5
- @SQReder $10

**Comment by phhusson** [comment]
I'm in for this bug bunty for 5$

**Comment by SQReder** [comment]
Hey. Wanna pay $10 for this fix

**Comment by bigrammy** [comment]
Is this issue related to this fix here https://github.com/phhusson/treble_experimentations/issues/392#issuecomment-462133993

**Comment by phhusson** [comment]
@bigrammy sadly no, this issue is specific to RIL vendor.mediatek.hardware.radio@2.6, which is only for the most recent mediatek firmwares, so not for Android 8.0 vendor

**Comment by phhusson** [comment]
This issue should be fixed in https://github.com/phhusson/platform_frameworks_opt_telephony/commit/d6dc72f72cad2f8ce038a6d9c3dc79e8f8be0a33

**Comment by ironashram** [comment]
> 
> 
> This issue should be fixed in [phhusson/platform_frameworks_opt_telephony@d6dc72f](https://github.com/phhusson/platform_frameworks_opt_telephony/commit/d6dc72f72cad2f8ce038a6d9c3dc79e8f8be0a33)

mt6771(bv9600pro) vendor 8.1, commit phhusson/platform_frameworks_opt_telephony@d6dc72f fixed mobile data, but incoming sms still won't work

**Comment by kzull** [comment]
I have the same problem.

**Comment by penn5** [comment]
@phhusson don't you win the bounty?

**Comment by ren321** [comment]
https://raw.githubusercontent.com/Havoc-OS/android_frameworks_opt_telephony/pie/src/java/com/android/internal/telephony/dataconnection/DcTracker.java
