### ISSUE TITLE
MTK no mobile data, no incoming SMS with Oreo+Pie 

### ISSUE THREAD

**Issue by sararah7** [phhusson/treble_experimentations#406]
Testing with six different devices which have the popular SoC MTK MT6739 in use.

Each has same result.

I keep foreceencrypt in fstab because we lose IMEI out cannot read our of not encrypted nv... partition.

Result is the same on each of the devices with that SoC:

Phone works,
SMS out works,
SMS in not works,
Mobile data not works.

In sim status info, I can see mobile data connecting for minutes, then disconnected.

Tried with 4G, 3G, 2G - none works with mobile data.

All logs are full of

>  E ProxyController: ERROR: sending down the same id for different phones

Thanks for the great work on the treble project support.

**Comment by sararah7** [comment]
May be related to #57

**Comment by bigrammy** [comment]
> May be related to #57

phhusson just posted this reply in a related issue https://github.com/phhusson/treble_experimentations/issues/373 so maybe it will fix your issue too.

**Comment by phhusson** [comment]
Yeah I also have mobile data fixed too.
@sararah7 please send me a mail to phh@phh.me, I'll send you a test image

**Comment by sararah7** [comment]
@phhusson i sent an email and can test it.

**Comment by stevea76** [comment]
I would be willing to test as well may I request test image via email @phhusson

**Comment by dumle11** [comment]
I have same issue, just send an email to @phhusson 
Using MTK6753. No Mobile/Calls/Text, IMEI Detected, WiFi Working, Bluetooth Working.

**Comment by phhusson** [comment]
That's NOT the same issue. In the bug mentioned here, mobile does work.

**Comment by dumle11** [comment]
> That's NOT the same issue. In the bug mentioned here, mobile does work.

Thanks for the reply. Should I open a new Issue for this problem, or would you possible have a solution already?

Here is logcat of radio:
[radio_logcat.txt](https://github.com/phhusson/treble_experimentations/files/2922247/radio_logcat.txt)

**Comment by phhusson** [comment]
@sararah7 this issue is fixed in v111 right?

**Comment by sararah7** [comment]
@phhusson not fully fixed, depends on where i insert the sim card, in sim1 or sim2. only one of it is able to receive SMS. only one has data with 3g/4g. the other is ok with data.

**Comment by oscx** [comment]
@phhusson I have tested with the new build v30. This is sticking to 2G again, only alternative SIM slot connecting 3G/4G. Is there input like `logcat -b radio` or similar which could be helpful or something to test for supporting a fix? Thank you!

**Comment by oscx** [comment]
@phhusson do You think there is a chance for resolving this or better to forget about this dual sim SoC, dead-end road?

**Comment by phhusson** [comment]
There is no software issue that can't be solved. I personally don't really plan on spending time on that issue. But then, I'm not the only dev in the world, you can probably motivate someone else with that issue.

**Comment by oscx** [comment]
ok, thanks. in my case, it might be easier and faster to migrate to another SoC. any way, i'll continue testing on new phh treble releases with that problem chip, too.

**Comment by bigrammy** [comment]
We have problems getting ril to work on a straight forward port of a sony 7.0 mtk device with some top class dev's working on it and yet it seems to elude all so to expect @phhusson to fix all in a one hit is near impossible.
I cannot get my head around how all this ril stuff works & to solve all the issues you would really need to replace the mtk ril with some something else.
This is all OEM's rather than MTK as some devices have no issue with ril if ported correctly yet other devices like our sony's simply do not work & who knows why or how they kill the rill on none stock builds. 
Let me know if anyone solves this riddle :+1:
