### ISSUE TITLE
Fingerprint dont work and settings force close after setting lockscreen on S9+

### ISSUE THREAD

**Issue by Elcid016** [phhusson/treble_experimentations#443]
after i try to add fingerprint or any type of lockscreen it will force close and after i reboot, whent it boots again system ui start to crash on lockscreen every second

Galaxy s9+ qualcomm star2qlte 
Pie vendor CSB3
here the logs
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2986146/logcat.txt)

**Comment by Elcid016** [comment]
> Uh... That's on my AOSP GSI ROM?

with all gsis i try the same happens

**Comment by phhusson** [comment]
well I need logs on my GSI
The stacktrace references lines that doesn't exist on my GSI.

**Comment by Elcid016** [comment]
ok i will send

**Comment by Elcid016** [comment]
[logcat setting lockscreen and fingerprint.txt](https://github.com/phhusson/treble_experimentations/files/3005351/logcat.setting.lockscreen.and.fingerprint.txt)
[logcat after reeboot systemui crash.txt](https://github.com/phhusson/treble_experimentations/files/3005352/logcat.after.reeboot.systemui.crash.txt)

**Comment by Elcid016** [comment]
i did two logs  one setting patter and fingerprint and other after reeboot when system ui start to crash on lockscree

**Comment by phhusson** [comment]
Now same thing without magisk...

**Comment by Elcid016** [comment]
[logcat setting patern and fingerprint.txt](https://github.com/phhusson/treble_experimentations/files/3005400/logcat.setting.patern.and.fingerprint.txt)
[logcat lockscreen crashing after reboot.txt](https://github.com/phhusson/treble_experimentations/files/3005402/logcat.lockscreen.crashing.after.reboot.txt)

**Comment by Elcid016** [comment]
done did a factory reset and restored stock kernel without magisk

**Comment by phhusson** [comment]
Please give me the result of "mount" when running my GSI

**Comment by Elcid016** [comment]
[mount.txt](https://github.com/phhusson/treble_experimentations/files/3005437/mount.txt)

**Comment by phhusson** [comment]
first the file is truncated
then, it looks like you have something like magisk still installed (could be something else than magisk?)

**Comment by Elcid016** [comment]
[mount stock.txt](https://github.com/phhusson/treble_experimentations/files/3005504/mount.stock.txt)
 this one full stock

**Comment by phhusson** [comment]
Edit /system/bin/rw-system.sh and remove line 26:
```        getprop ro.vendor.build.fingerprint | grep -qiE '^samsung/' && return 0```

**Comment by Elcid016** [comment]
done

**Comment by phhusson** [comment]
I'm guessing this means it still doesn't work...?
can you give me the result of "mount" command after that change?

**Comment by Elcid016** [comment]
[mount 2.txt](https://github.com/phhusson/treble_experimentations/files/3005681/mount.2.txt)

**Comment by Elcid016** [comment]
> I'm guessing this means it still doesn't work...?
> can you give me the result of "mount" command after that change?

yep dont work

**Comment by Elcid016** [comment]
@phhusson any ideia what we could do

**Comment by Elcid016** [comment]
here the log of fingerprint and lockscreen on stock 
[fingerprintlog stock.txt](https://github.com/phhusson/treble_experimentations/files/3036014/fingerprintlog.stock.txt)

and i didi a dump of stock rom system and vendor iff u need https://drive.google.com/open?id=1x1AeuU6cekAQzNu6p7mexLTSYhtREVqv
