### ISSUE TITLE
[Pixel 2 XL] Fix in-call audio

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#88]
Pixel 2 XL (and probably all 4 current Pixels), have the Qualcomm audio issue, fixed in:
https://github.com/phhusson/vendor_hardware_overlay/commit/b213495933d28cd50d9dc76e4fa920bb8b03836d#diff-4d4cb726a6468099c7bd25a3e60deae1

But with a minor difference:
-import vendor.qti.hardware.radio.am.V1_0.IQcRilAudioCallback;
-import vendor.qti.hardware.radio.am.V1_0.IQcRilAudio;
+import vendor.qti.qcril.am.V1_0.IQcRilAudioCallback;
+import vendor.qti.qcril.am.V1_0.IQcRilAudio;

(vendor.qti.qcrim.am.V1_0 compatibility has been confirmed)

This needs to rework a bit Service.java to handle that.

**Comment by sjdrc** [comment]
Hey, if there's anything I can do to help out with this issue, I'd be happy to assist.

**Comment by phhusson** [comment]
https://github.com/phhusson/vendor_hardware_overlay/commit/9027696ac7af7cc6cb4f3b4f36fd3210696a9ffa
This should do the trick
not tested yet though

**Comment by sooti** [comment]
Pixel Sailfish is still broken

**Comment by jamuir** [comment]
I have a sailfish device and just tested a phh gsi built locally (on 28 June 2018).  I can confirm that in-call audio is broken.

The defect is related to selinux.  You can work around it like this:

```base
$ adb root
$ adb shell stop
$ adb shell setenforce 0
$ adb shell start
```
I have a fix for this in my own gsi tree, but my tree does not use `vendor/hardware_overlay/Qualcomm/QtiAudio` -- I am using the qualcomm apk from the factory vendor image.  @phhusson I can give you more details in the telegram-group.

**Comment by phhusson** [comment]
:( I should have tested better

Thanks for the reports

**Comment by phhusson** [comment]
Should be fixed with https://github.com/phhusson/device_phh_treble/commit/9b1ab76f4416a0e889932867901b5cbc0b6fbf45
I got lucky and found that Pixel 1 and Pixel 2 have different SELinux settings...

**Comment by sooti** [comment]
still not fixed, we need to add a couple more exceptions i believe

[    8.055330] type=1400 audit(56109340.840:76): avc: denied { ioctl } for pid=795 comm="rild" path="/vendor/qcril.db" dev="sda32" ino=570 ioctlcmd=f50c scontext=u:r:rild:s0 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0

[    7.462715] type=1400 audit(56109340.180:74): avc: denied { search } for pid=728 comm="audio@2.0-servi" name="audio" dev="sda35" ino=2359366 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:audio_data_file:s0 tclass=dir permissive=0 duplicate messages suppressed

**Comment by phhusson** [comment]
https://android.googlesource.com/device/google/marlin/+/master/sepolicy/rild.te#33

In master there is
https://android.googlesource.com/device/google/marlin/+/master/sepolicy/hal_audio_default.te#13
But I don't see such a thing in 8.1 branch

Can you set selinux to permissive and get full logs?
There are probably many more fails

**Comment by phhusson** [comment]
Is this issue still relevant?
